### PR TITLE
Add support for function components (and rewrite in typescript)

### PR DESCRIPTION
**Pull request by eikhr**
This pull request got a bit large, but basically what I've done is:

1. Bumped all the dependencies
This wasn't strictly necessary, as almost nothing is used outside of development. But it made things a bit easier to work with, and got rid of a bunch of vulnerability warnings. During this process I also updated the linting and babel configs. 
2. Convert everything to typescript
This is most of the changes. I ended up refactoring quite a bit of code to make it more compatible with typescript, and a bit easier to work with.
3. Finally I fixed the functional components with hooks
This was a bit tricky as my knowledge of how node-modules work turned out to be a bit lacking. Once I figured out some problems with multiple instances of react, however, the fix was fairly simple. I found this package [react-shallow-renderer](https://github.com/enzymejs/react-shallow-renderer), that does exactly what we need in the prepare method. And it has perfect support for function components with hooks 😁. 

One thing to note is that useEffects are not run when server-side rendering, as they are first run after the inital render, like componentDidMount() (not like componentWillMount()).

### CODE REVIEW

**Review by LudvigHz — CHANGES_REQUESTED** [review]
You need to clean up the commits here, otherwise it's impossible to review :upside_down_face: :grimacing: .

Please make sure:
- all changes to dependecies, development tooling and the like are in seperate commits
- Everything to do with typescript is in seperate commits. These should not touch the logic of the code pls. (it looks okay, but I can't really tell since the diff is not rendered as renamed in the relevant commit)
- All commits to do with logic and code changes should come after, preferably in some logical pieces

If you want to move the typescript stuff to another PR, that's also fine (tbh alot better). But It doesn't really matter as long as the changes are separated in some form.

Also make sure you `git mv` in one commit and edit the moved file in another so you don't break history. (As it is now, the diff is "prepared.js deleted", "prepared.tsx added". And this way I can't tell what you've done without validating manually that there are no logic changes in the commit that does the delete and add. if you `git mv`, `git commit`, `<edit the file>` and then `git commit`, that should fix it :tm:.

It seems it almost good, just make sure the that the file renaming is good, and the other commits make sense by themselves, so I can review commit by commit (or similar). Some context for the changes in the commits would be nice as well :)

Also, could you give a not-so-brief explanation of why this now works with hooks and what `react-shallow-renderer` does for us. Also why we need it. I.e. a short explanation of the _problem_, what needs to be done to fix it, and how your changes fixes said problem :)


Otherwise really cool! :100: Can't say I understand why, or see the need to make it TS :shrug:, but if this works with hooks without any unwanted consequences, that's awesome :heart_eyes:!

**Comment by eikhr** [comment]
Yea, the typescript was definitely unnecessary. I mostly did it to gain a better understanding of the code, as it was fairly hard to understand. I also learned alot about typescript :)

I will split it up and clean up the commits. I agree it must be done, but it's so boooring :(
The trick for not breaking git history was cool tho, I didn't know you could do that!

**Comment by eikhr** [comment]
Basically the way `react-prepare` works is that the app using it can add a prepare-function to components that is run before server-side rendering. This is normally used to fetch data. 

When react-prepare is preparing the app, it recursively goes through the children of all components, looking for prepare-functions it needs to run. Because the prepare-functions are run with the components' props, `react-prepare` needs to run the render function of each component, such that the children props are calculated.
For normal components this is as simple as runnning render(), or simply running the function component (and there are a few special cases already for other component types). But when the component contains a hook, running the function will cause an error because react needs to do some setup first. `react-shallow-renderer` fixes this problem by doing the necessary setup, and then rendering the component "shallowly", aka. only one level deep. Exactly what we want. We can then get the children components with props from the ShallowRenderer. 

In essence, `react-prepare` has implemeted a very simple shallow renderer manually, but with the added complexity of hooks, it is a lot easier to use `react-shallow-renderer`

**Comment by LudvigHz** [comment]
> But when the component contains a hook, running the function will cause an error because react needs to do some setup first. 

I see, this was the what I was wondering about. I've been taking a look around in the codebases of `react` and `react-shallow-renderer` and it looks to me like the issue we have is that we have no `dispatcher`, which is a "thing" in the react renderer responsible for dispatching and handling hooks in function components.

So:
1. The error originates from https://github.com/facebook/react/blob/0568c0f8cde4ac6657dff9a5a8a7112acc35a748/packages/react/src/ReactHooks.js#L29
2. The error refers to the fact that there is no currently defined _dispatcher_, indicated by [`ReactCurrentDispatcher`](https://github.com/facebook/react/blob/0568c0f8cde4ac6657dff9a5a8a7112acc35a748/packages/react/src/ReactCurrentDispatcher.js), which keeps track of the current dispatcher in react.  The dispatcher is set by whatever rendering engine is used. (i.e. `react-DOM`, `react-native` etc)
3. `react-shallow-renderer` has implemented a very simple dispatcher they use when rendering: https://github.com/enzymejs/react-shallow-renderer/blob/802c735ee53bf2d965797760698cacbd46088f66/src/ReactShallowRenderer.js#L185
4. You can see another example implementation of some dispatchers in `react-reaconciler`, f.ex. https://github.com/facebook/react/blob/d5f1b067c8bbb826b823d0354a28ba31078b70c0/packages/react-reconciler/src/ReactFiberHooks.new.js#L2537

In conclusion, we don't need a full render-capable dispatcher, just something that can evaluate the data-flow to the child component so we can continue traversing the tree with our data. Whatever hooks are defined on the component, we just care about _if_ the props given to the component are used further down in the rendering. I.e. we can ignore `useEffect` and some other hooks. Others, like `useMemo` just need to return the same value, as with `useContext` etc.

### Conclusion
So. The case that needs to be discussed and validated is this:
We could implement a _simple_ dispatcher that just does what we need it to, similar to `react-shallow-renderer`. (I see you have already implemented the dispatcher for `useContext`, so that's good piece done :1st_place_medal:) 
**OR** we could just use `react-shallow-renderer` as you have done here, and rely on that for our dispatcher.

**I'm open to both but here are my thoughts:**
- Relying on yet another package (that is very rarely updated) could pose an issue and is another "black box"
- However, _if_ `react-shallow-renderer` updates their code along with potential react API changes (I don't really see react changing the API anytime soon though) we will benefit from that.
- Another thing we can possibly do, is just use the dispatcher from `react-shallow-renderer` and discard the whole "rendering" part.
- Speed: So, with the shallow renderer, we do alot of unnecessary calls. It's not _that_ much, but I am interested to see if there's any difference in performance anyways, since it does do quite a bit "extra" work that we don't need compared to before/not using it.
- Considering you _already_ have implemented our own dispatcher for `useContext`, we're just missing `useReducer` (need to do some investigating when this runs, I suspect we can just use the initial value), `useState` (which just needs to return the initial value), and the rest should be quite simple.
- Implementing this logic ourselves requires it to work. Considering we know that the current proposed implementation works, we risk our own implementation not working. Although, AFAIK regular function components (without hooks) has always worked? So if we get the hooks thing right, it should work? And as far as I see in `react-shallow-renderer`s code, the only thing they do different from us is creating and assigning the dispatcher.

**Comment by eikhr** [comment]
Ok, I guess I should have gone more in depth.

Yes, I am aware that the problem originates in the fact that we are missing a `dispatcher`. I did actually start implementing a custom dispatcher first, but abandoned it because I discovedered `react-shallow-renderer`. I have since realized though, that my custom dispatcher could be implemented a lot simpler than what i did, as there is no reason to support useEffect, and thererfore impossible, as far as i can tell, to cause a rerender. So a custom dispatcher is a perfectly viable solution.

As you mentioned, we have two options. 
1. We use `react-shallow-renderer`
This might have some performance downsides. I will try looking into this. On the other hand it is likely more robust then our very simple custom rendering, and is somewhat regularily maintained (it has recently been updated with basic react 18 support). 
2. We add a very simple custom dispatcher
This is a bit more work, but it would allow us to tailor the rendering to our needs. We would then rely on us to update it whenever there are API-changes or new features in react, something we have not been very good at earlier.

In my opinion it really comes down to the performance. If it is an issue it shouldn't be too hard to implement our own dispatcher. But if not, it seems like a simpler option to just use `react-shallow-renderer`. Assuming it is maintained, we could in theory just bump it to support new react versions. We could probably also simplify a lot of the other prepare-logic, as all the shallow rendering could be done by `react-shallow-renderer`.

**Comment by eikhr** [comment]
Closing this as the functionality is implemented in #18. This does, however, contain typescript types for most of the package, so that might (or might not) be worth finishing and creating a pull-request for at some point.

**Pull request closed without merging**
